### PR TITLE
Add a license

### PR DESCRIPTION
**Pull request by aroben**
This is the same 3-clause BSD license used by https://github.com/mokus0/monad-loops.

We'd like to use this bundle for highlighting Agda code on github.com using the new syntax highlighter we've been developing. Would you be willing to add a license? Thanks!

### CODE REVIEW

**Comment by aroben** [comment]
Hi, just leaving a friendly ping on this PR. Does the license look acceptable to you?

**Comment by aroben** [comment]
Hi again, any chance this could be merged? If you'd prefer a different license I'm happy to change it!

**Comment by mokus0** [comment]
Thanks, and sorry it took so long to merge.  Haven't checked my email in ages.

**Comment by aroben** [comment]
No worries, and thank you!

**Pull request merged**
